# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exercies.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_inspiring(object):
    def setupUi(self, inspiring):
        inspiring.setObjectName("inspiring")
        inspiring.resize(1000, 800)
        inspiring.setMinimumSize(QtCore.QSize(1000, 800))
        inspiring.setMaximumSize(QtCore.QSize(1000, 800))
        inspiring.setStyleSheet("background-color: rgb(47, 163, 209);")
        self.label = QtWidgets.QLabel(inspiring)
        self.label.setGeometry(QtCore.QRect(380, 60, 221, 191))
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/new_pic.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.stress = QtWidgets.QFrame(inspiring)
        self.stress.setGeometry(QtCore.QRect(160, 300, 661, 321))
        self.stress.setStyleSheet("background-color: rgb(61, 220, 255);\n"
"border-radius: 10px;")
        self.stress.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.stress.setFrameShadow(QtWidgets.QFrame.Raised)
        self.stress.setObjectName("stress")
        self.label_2 = QtWidgets.QLabel(self.stress)
        self.label_2.setGeometry(QtCore.QRect(40, 50, 451, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.back = QtWidgets.QPushButton(self.stress)
        self.back.setGeometry(QtCore.QRect(40, 260, 181, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.back.setFont(font)
        self.back.setStyleSheet("QPushButton {\n"
"    background-color: #fdfcfa;\n"
"    border: 1px solid #0c253b;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* Add styling for when the button is pressed */\n"
"    background-color: #c0c0c0; /* For example, change the background color when pressed */\n"
"}")
        self.back.setObjectName("back")
        self.next = QtWidgets.QPushButton(self.stress)
        self.next.setGeometry(QtCore.QRect(230, 260, 191, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.next.setFont(font)
        self.next.setStyleSheet("QPushButton {\n"
"    background-color: #fdfcfa;\n"
"    border: 1px solid #0c253b;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* Add styling for when the button is pressed */\n"
"    background-color: #c0c0c0; /* For example, change the background color when pressed */\n"
"}")
        self.next.setObjectName("next")
        self.MainMenu = QtWidgets.QPushButton(self.stress)
        self.MainMenu.setGeometry(QtCore.QRect(430, 260, 191, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.MainMenu.setFont(font)
        self.MainMenu.setStyleSheet("QPushButton {\n"
"    background-color: #fdfcfa;\n"
"    border: 1px solid #0c253b;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    /* Add styling for when the button is pressed */\n"
"    background-color: #c0c0c0; /* For example, change the background color when pressed */\n"
"}")
        self.MainMenu.setObjectName("MainMenu")
        self.image = QtWidgets.QLabel(self.stress)
        self.image.setGeometry(QtCore.QRect(420, 80, 201, 161))
        self.image.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.image.setText("")
        self.image.setObjectName("image")
        self.exercies = QtWidgets.QLabel(self.stress)
        self.exercies.setGeometry(QtCore.QRect(30, 80, 381, 161))
        self.exercies.setStyleSheet("background-color: rgb(242, 217, 170);")
        self.exercies.setText("")
        self.exercies.setObjectName("exercies")

        self.retranslateUi(inspiring)
        QtCore.QMetaObject.connectSlotsByName(inspiring)

    def retranslateUi(self, inspiring):
        _translate = QtCore.QCoreApplication.translate
        inspiring.setWindowTitle(_translate("inspiring", "Form"))
        self.label_2.setText(_translate("inspiring", "Stress Relief Exercies"))
        self.back.setText(_translate("inspiring", "Back"))
        self.next.setText(_translate("inspiring", "Next"))
        self.MainMenu.setText(_translate("inspiring", "Main Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    inspiring = QtWidgets.QWidget()
    ui = Ui_inspiring()
    ui.setupUi(inspiring)
    inspiring.show()
    sys.exit(app.exec_())
