# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resorces.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

from config import logo_path
from src.resources import Resources, ResourcesFunction
import webbrowser

class Ui_inspiring(object):
    def __init__(self) -> None:
        self.function = ResourcesFunction()
        self.current_index = 0


from src.resources import Resources


class Ui_resorces(QtWidgets.QWidget):
    def __init__(self, parent_page) -> None:
        super().__init__()
        self.functions = ResourcesFunction()
        self.parent_page = parent_page

    def setupUi(self, inspiring):
        inspiring.setObjectName("inspiring")
        inspiring.resize(1000, 800)
        inspiring.setMinimumSize(QtCore.QSize(1000, 800))
        inspiring.setMaximumSize(QtCore.QSize(1000, 800))
        inspiring.setStyleSheet("background-color: rgb(47, 163, 209);")
        self.label = QtWidgets.QLabel(inspiring)
        self.label.setGeometry(QtCore.QRect(370, 70, 221, 191))
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(logo_path))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(inspiring)
        self.frame.setGeometry(QtCore.QRect(170, 320, 611, 331))
        self.frame.setStyleSheet("background-color: rgb(61, 220, 255);\n"
                                 "border-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(80, 40, 451, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.back = QtWidgets.QPushButton(self.frame)
        self.back.clicked.connect(self.on_back_pressed)
        self.back.setGeometry(QtCore.QRect(50, 270, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.back.setFont(font)
        self.back.setStyleSheet("QPushButton {\n"
                                "    background-color: #fdfcfa;\n"
                                "    border: 1px solid #0c253b;\n"
                                "    border-radius: 10px;\n"
                                "}\n"
                                "\n"
                                "QPushButton:pressed {\n"
                                "    /* Add styling for when the button is pressed */\n"
                                "    background-color: #c0c0c0; /* For example, change the background color when pressed */\n"
                                "}")
        self.back.setObjectName("back")
        self.next = QtWidgets.QPushButton(self.frame)
        self.next.clicked.connect(self.on_next_pressed)
        self.next.setGeometry(QtCore.QRect(310, 270, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.next.setFont(font)
        self.next.setStyleSheet("QPushButton {\n"
                                "    background-color: #fdfcfa;\n"
                                "    border: 1px solid #0c253b;\n"
                                "    border-radius: 10px;\n"
                                "}\n"
                                "\n"
                                "QPushButton:pressed {\n"
                                "    /* Add styling for when the button is pressed */\n"
                                "    background-color: #c0c0c0; /* For example, change the background color when pressed */\n"
                                "}")
        self.next.setObjectName("next")
        self.mainMenu = QtWidgets.QPushButton(self.frame)

        def on_main_menu_clicked():
            if self.parent_page is not None:
                window = QtWidgets.QMainWindow()
                self.parent_page.setupUi(window)
                window.show()
                inspiring.close()

        self.mainMenu.clicked.connect(on_main_menu_clicked)
        self.mainMenu.setGeometry(QtCore.QRect(410, 280, 161, 31))

        self.mainMenu.setGeometry(QtCore.QRect(440, 270, 121, 21))

        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.mainMenu.setFont(font)
        self.mainMenu.setStyleSheet("QPushButton {\n"
                                    "    background-color: #fdfcfa;\n"
                                    "    border: 1px solid #0c253b;\n"
                                    "    border-radius: 10px;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:pressed {\n"
                                    "    /* Add styling for when the button is pressed */\n"
                                    "    background-color: #c0c0c0; /* For example, change the background color when pressed */\n"
                                    "}")
        self.mainMenu.setObjectName("mainMenu")
        self.open_video = QtWidgets.QPushButton(self.frame)
        self.open_video.setGeometry(QtCore.QRect(180, 270, 121, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.open_video.setFont(font)
        self.open_video.setStyleSheet("QPushButton {\n"
                                      "    background-color: #fdfcfa;\n"
                                      "    border: 1px solid #0c253b;\n"
                                      "    border-radius: 10px;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "    /* Add styling for when the button is pressed */\n"
                                      "    background-color: #c0c0c0; /* For example, change the background color when pressed */\n"
                                      "}")
        self.open_video.setObjectName("open_video")
        self.image = QtWidgets.QLabel(self.frame)
        self.image.setScaledContents(True)
        self.image.setGeometry(QtCore.QRect(400, 100, 161, 151))
        self.image.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.image.setText("")
        self.image.setObjectName("image")
        self.description_text = QtWidgets.QLabel(self.frame)
        self.description_text.setGeometry(QtCore.QRect(40, 100, 351, 151))
        self.description_text.setStyleSheet("background-color: rgb(242, 217, 170);font-size: 12pt;")
        self.description_text.setText("")
        self.description_text.setObjectName("description_label")
        self.description_text.setWordWrap(True)
        self.set_resource(self.functions.current_resource())

        self.retranslateUi(inspiring)
        QtCore.QMetaObject.connectSlotsByName(inspiring)

    def retranslateUi(self, inspiring):
        _translate = QtCore.QCoreApplication.translate
        inspiring.setWindowTitle(_translate("inspiring", "Form"))
        self.label_2.setText(_translate("inspiring", "External Resorces"))
        self.back.setText(_translate("inspiring", "Back"))
        self.next.setText(_translate("inspiring", "Next"))
        self.mainMenu.setText(_translate("inspiring", "Main Menu"))
        self.open_video.setText(_translate("inspiring", "Open video"))
        self.open_video.clicked.connect(self.on_open_video_pressed)


    def set_resource(self, resource: Resources):
        if resource is not None:
            image = resource.image_path
        if image:
            pixmap = QtGui.QPixmap(image)
            self.image.setPixmap(pixmap)
        self.description_text.setText(resource.description)

    def on_next_pressed(self):
        resource = self.functions.next_resource()
        if resource is not None:
            self.set_resource(resource)

    def on_back_pressed(self):
        resource = self.functions.previous_resource()
        if resource is not None:
            self.set_resource(resource)

    def on_open_video_pressed(self):
        video = self.functions.current_resource().video_link
        webbrowser.open(f'{video}')


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    inspiring = QtWidgets.QWidget()
    ui = Ui_resorces(None)
    ui.setupUi(inspiring)
    inspiring.show()
    sys.exit(app.exec_())
