# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 ui code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from config import logo_path
from .inspiring import Ui_inspiring
from .stress import Ui_stress
from .support import Ui_Support
from .music import Ui_Music
from .external_resources import Ui_resorces
from PyQt5.QtWidgets import QDialog


class Ui_MainWindow(QDialog):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 800))
        MainWindow.setStyleSheet("background-color: rgb(47, 163, 209);")
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(360, 40, 231, 211))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(logo_path))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(300, 270, 351, 351))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.inspiring = QtWidgets.QPushButton(self.frame)
        self.inspiring.clicked.connect(lambda: self.navigate(MainWindow, Ui_inspiring(self)))
        self.inspiring.setEnabled(True)
        self.inspiring.setGeometry(QtCore.QRect(0, 10, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic ui Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.inspiring.setFont(font)
        self.inspiring.setStyleSheet("QPushButton {\n"
                                     "    background-color: #fdfcfa;\n"
                                     "    border: 1px solid #0c253b;\n"
                                     "    border-radius: 10px;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:pressed {\n"
                                     "    /* Add styling for when the button is pressed */\n"
                                     "    background-color: #c0c0c0; /* For example, change the background color when pressed */\n"
                                     "}\n"
                                     "\n"
                                     "\n"
                                     "\n"
                                     "")
        self.inspiring.setAutoDefault(False)
        self.inspiring.setDefault(False)
        self.inspiring.setFlat(False)
        self.inspiring.setObjectName("inspiring")
        self.stress = QtWidgets.QPushButton(self.frame)
        self.stress.clicked.connect(lambda: self.navigate(MainWindow, Ui_stress(self)))
        self.stress.setEnabled(True)
        self.stress.setGeometry(QtCore.QRect(0, 70, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic ui Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.stress.setFont(font)
        self.stress.setStyleSheet("QPushButton {\n"
                                  "    background-color: #fdfcfa;\n"
                                  "    border: 1px solid #0c253b;\n"
                                  "    border-radius: 10px;\n"
                                  "}\n"
                                  "\n"
                                  "QPushButton:pressed {\n"
                                  "    /* Add styling for when the button is pressed */\n"
                                  "    background-color: #c0c0c0; /* For example, change the background color when pressed */\n"
                                  "}\n"
                                  "\n"
                                  "\n"
                                  "")
        self.stress.setObjectName("stress")
        self.resorces = QtWidgets.QPushButton(self.frame)
        self.resorces.clicked.connect(lambda: self.navigate(MainWindow, Ui_resorces(self)))
        self.resorces.setEnabled(True)
        self.resorces.setGeometry(QtCore.QRect(0, 130, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic ui Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.resorces.setFont(font)
        self.resorces.setStyleSheet("QPushButton {\n"
                                    "    background-color: #fdfcfa;\n"
                                    "    border: 1px solid #0c253b;\n"
                                    "    border-radius: 10px;\n"
                                    "}\n"
                                    "\n"
                                    "QPushButton:pressed {\n"
                                    "    /* Add styling for when the button is pressed */\n"
                                    "    background-color: #c0c0c0; /* For example, change the background color when pressed */\n"
                                    "}\n"
                                    "\n"
                                    "\n"
                                    "")
        self.resorces.setObjectName("resorces")
        self.music = QtWidgets.QPushButton(self.frame)
        self.music.clicked.connect(lambda: self.navigate(MainWindow, Ui_Music(self)))
        self.music.setEnabled(True)
        self.music.setGeometry(QtCore.QRect(0, 190, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic ui Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.music.setFont(font)
        self.music.setStyleSheet("QPushButton {\n"
                                 "    background-color: #fdfcfa;\n"
                                 "    border: 1px solid #0c253b;\n"
                                 "    border-radius: 10px;\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton:pressed {\n"
                                 "    /* Add styling for when the button is pressed */\n"
                                 "    background-color: #c0c0c0; /* For example, change the background color when pressed */\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "")
        self.music.setObjectName("music")
        self.support = QtWidgets.QPushButton(self.frame)
        self.support.clicked.connect(lambda: self.navigate(MainWindow, Ui_Support(self)))
        self.support.setEnabled(True)
        self.support.setGeometry(QtCore.QRect(0, 250, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic ui Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.support.setFont(font)
        self.support.setStyleSheet("QPushButton {\n"
                                   "    background-color: #fdfcfa;\n"
                                   "    border: 1px solid #0c253b;\n"
                                   "    border-radius: 10px;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:pressed {\n"
                                   "    /* Add styling for when the button is pressed */\n"
                                   "    background-color: #c0c0c0; /* For example, change the background color when pressed */\n"
                                   "}\n"
                                   "\n"
                                   "\n"
                                   "")
        self.support.setObjectName("support")
        self.exit = QtWidgets.QPushButton(self.frame)
        self.exit.setEnabled(True)
        self.exit.setGeometry(QtCore.QRect(0, 310, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic ui Semibold")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.exit.setFont(font)
        self.exit.setStyleSheet("QPushButton {\n"
                                   "    background-color: #fdfcfa;\n"
                                   "    border: 1px solid #0c253b;\n"
                                   "    border-radius: 10px;\n"
                                   "}\n"
                                   "\n"
                                   "QPushButton:pressed {\n"
                                   "    /* Add styling for when the button is pressed */\n"
                                   "    background-color: #c0c0c0; /* For example, change the background color when pressed */\n"
                                   "}\n"
                                   "\n"
                                   "\n"
                                   "")
        self.exit.setObjectName("Exit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.inspiring.setText(_translate("MainWindow", "Inspiring Quotes"))
        self.stress.setText(_translate("MainWindow", "Stress Relief Exercise"))
        self.resorces.setText(_translate("MainWindow", "External Resorces"))
        self.music.setText(_translate("MainWindow", "A list of Music"))
        self.support.setText(_translate("MainWindow", "Support"))
        self.exit.setText(_translate("MainWindow", "Exit"))
        self.exit.clicked.connect(MainWindow.close)



    def navigate(self, current_window, page: QtWidgets.QWidget):
        new_window = QtWidgets.QMainWindow()
        page.setupUi(new_window)
        new_window.show()
        current_window.hide()



if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
